#!/usr/bin/env python3
import argparse
import html
import json
import pathlib
import shlex
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
INFO_PATH = ROOT / "info.json"
CHANGELOG_PATH = ROOT / "changelog.txt"
COPY_PATH = ROOT / "docs" / "public-copy.json"
SITE_PATH = ROOT / "docs" / "index.html"


def load_json(path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def parse_changelog(path):
    releases = []
    current = None
    current_category = None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if not stripped or set(stripped) == {"-"}:
            continue

        if stripped.startswith("Version:"):
            if current is not None:
                releases.append(current)
            current = {
                "version": stripped.split(":", 1)[1].strip(),
                "date": "",
                "categories": [],
            }
            current_category = None
            continue

        if current is None:
            continue

        if stripped.startswith("Date:"):
            current["date"] = stripped.split(":", 1)[1].strip()
            continue

        if line.startswith("  ") and stripped.endswith(":") and not stripped.startswith("-"):
            current_category = {"name": stripped[:-1], "items": []}
            current["categories"].append(current_category)
            continue

        if line.startswith("    - ") and current_category is not None:
            current_category["items"].append(line[6:])

    if current is not None:
        releases.append(current)

    if not releases:
        raise ValueError(f"No releases found in {path}")
    return releases


def validate_sources(info, latest_release):
    if info["version"] != latest_release["version"]:
        raise ValueError(
            "info.json version "
            f"{info['version']} does not match latest changelog version {latest_release['version']}"
        )


def e(value):
    return html.escape(str(value), quote=True)


def inline_html(value):
    parts = str(value).split("`")
    if len(parts) == 1:
        return e(value)

    output = []
    for index, part in enumerate(parts):
        if index % 2 == 0:
            output.append(e(part))
        else:
            output.append(f"<code>{e(part)}</code>")
    return "".join(output)


def lines_to_html_list(items, indent):
    lines = [f"{indent}<ul>"]
    for item in items:
        lines.append(f"{indent}  <li>{inline_html(item)}</li>")
    lines.append(f"{indent}</ul>")
    return lines


def render_changelog_html(release, indent):
    lines = [f"{indent}<div class=\"release-notes\">"]
    for category in release["categories"]:
        if not category["items"]:
            continue
        lines.append(f"{indent}  <h3>{e(category['name'])}</h3>")
        lines.extend(lines_to_html_list(category["items"], f"{indent}  "))
    lines.append(f"{indent}</div>")
    return lines


def render_site(info, copy, latest_release):
    title = info["title"]
    description = info["description"]
    lines = [
        "<!doctype html>",
        "<html lang=\"en\">",
        "  <head>",
        "    <meta charset=\"utf-8\">",
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        f"    <title>{e(title)}</title>",
        f"    <meta name=\"description\" content=\"{e(description)}\">",
        "    <link rel=\"stylesheet\" href=\"site.css\">",
        "  </head>",
        "  <body>",
        "    <!-- Generated by scripts/generate-public-assets.py from info.json, changelog.txt, and docs/public-copy.json. -->",
        "    <header class=\"site-header\">",
        f"      <a class=\"brand\" href=\"./\">{e(title)}</a>",
        "      <nav aria-label=\"Primary\">",
        "        <a href=\"#playtest\">Playtest</a>",
        "        <a href=\"#docs\">Docs</a>",
        f"        <a href=\"{e(copy['mod_portal_url'])}\">Mod Portal</a>",
        f"        <a href=\"{e(copy['source_url'])}\">Source</a>",
        "      </nav>",
        "    </header>",
        "",
        "    <main>",
        "      <section class=\"intro\" aria-labelledby=\"intro-title\">",
        "        <div class=\"intro-copy\">",
        f"          <p class=\"eyebrow\">{e(copy['intro']['eyebrow'])}</p>",
        f"          <h1 id=\"intro-title\">{e(title)}</h1>",
        f"          <p class=\"lede\">{e(copy['intro']['lede'])}</p>",
        "          <div class=\"actions\" aria-label=\"Project links\">",
        f"            <a class=\"button primary\" href=\"{e(copy['mod_portal_url'])}\">Download</a>",
        f"            <a class=\"button\" href=\"{e(copy['release_url'])}\">Latest Release</a>",
        "          </div>",
        "        </div>",
        "",
        "        <div class=\"panel-preview\" aria-label=\"Turret XP panel preview\">",
        f"          <div class=\"panel-title\">{e(title)}</div>",
        "          <div class=\"level-row\">",
        "            <strong>Level 3</strong>",
        "            <span>74 / 272 XP</span>",
        "          </div>",
        "          <div class=\"xp-bar\" aria-hidden=\"true\">",
        "            <span></span>",
        "          </div>",
        "          <div class=\"stats-grid\">",
        "            <span>HP</span><strong>400 / 400</strong>",
        "            <span>Shooting speed</span><strong>25/s</strong>",
        "            <span>Range</span><strong>18</strong>",
        "            <span>Magazine</span><strong>piercing x42</strong>",
        "            <span>Ammo</span><strong>10 / 10</strong>",
        "            <span>Est. DPS</span><strong>157.5/s</strong>",
        "            <span>Kills</span><strong>18</strong>",
        "            <span>Damage dealt</span><strong>3,860</strong>",
        "          </div>",
        "        </div>",
        "      </section>",
        "",
        "      <section class=\"band\" aria-labelledby=\"current-title\">",
        "        <div>",
        "          <p class=\"eyebrow\">Current release</p>",
        f"          <h2 id=\"current-title\">Version {e(latest_release['version'])}</h2>",
        f"          <p>{e(latest_release['date'])}</p>",
        "        </div>",
    ]
    lines.extend(render_changelog_html(latest_release, "        "))
    lines.extend(
        [
            "      </section>",
            "",
            "      <section class=\"content\" aria-labelledby=\"features-title\">",
            "        <h2 id=\"features-title\">What It Does</h2>",
            "        <div class=\"feature-grid\">",
        ]
    )
    for feature in copy["features"]:
        lines.extend(
            [
                "          <article>",
                f"            <h3>{e(feature['title'])}</h3>",
                f"            <p>{e(feature['body'])}</p>",
                "          </article>",
            ]
        )
    lines.extend(
        [
            "        </div>",
            "      </section>",
            "",
            "      <section id=\"playtest\" class=\"content split\" aria-labelledby=\"playtest-title\">",
            "        <div>",
            "          <h2 id=\"playtest-title\">Playtest Path</h2>",
            f"          <p>{e(copy['playtest']['intro'])}</p>",
            "        </div>",
            "        <ol class=\"steps\">",
        ]
    )
    for step in copy["playtest"]["steps"]:
        lines.append(f"          <li>{e(step)}</li>")
    lines.extend(
        [
            "        </ol>",
            "      </section>",
            "",
            "      <section id=\"docs\" class=\"content\" aria-labelledby=\"docs-title\">",
            "        <h2 id=\"docs-title\">Documentation</h2>",
            "        <div class=\"doc-grid\">",
        ]
    )
    for doc in copy["docs"]:
        lines.extend(
            [
                f"          <a href=\"{e(doc['href'])}\">",
                f"            <strong>{e(doc['title'])}</strong>",
                f"            <span>{e(doc['description'])}</span>",
                "          </a>",
            ]
        )
    lines.extend(
        [
            "        </div>",
            "      </section>",
            "    </main>",
            "",
            "    <footer>",
            f"      <span>{e(title)}</span>",
            f"      <a href=\"{e(copy['source_url'])}\">GitHub</a>",
            f"      <a href=\"{e(copy['mod_portal_url'])}\">Factorio Mod Portal</a>",
            "    </footer>",
            "  </body>",
            "</html>",
            "",
        ]
    )
    return "\n".join(lines)


def render_changelog_markdown(release):
    lines = [f"## Changes In {release['version']} ({release['date']})", ""]
    for category in release["categories"]:
        if not category["items"]:
            continue
        lines.extend([f"### {category['name']}", ""])
        lines.extend(f"- {item}" for item in category["items"])
        lines.append("")
    return "\n".join(lines).rstrip()


def render_portal_description(info, copy, latest_release):
    lines = [f"# {info['title']}", ""]
    for paragraph in copy["portal_description"]["paragraphs"]:
        lines.extend([paragraph, ""])
    lines.extend(["Highlights:", ""])
    lines.extend(f"- {item}" for item in copy["highlights"])
    lines.extend(["", render_changelog_markdown(latest_release), ""])
    lines.extend(["Source:", copy["source_url"], ""])
    lines.extend(["Homepage:", copy["homepage_url"], ""])
    return "\n".join(lines)


def render_release_notes(info, copy, latest_release):
    lines = [f"# {info['title']} {info['version']}", "", copy["release_notes"]["intro"], ""]
    lines.extend(["## Highlights", ""])
    lines.extend(f"- {item}" for item in copy["highlights"])
    lines.extend(["", render_changelog_markdown(latest_release), ""])
    lines.extend(["## Validation", ""])
    lines.extend(f"- {item}" for item in copy["release_notes"]["validation"])
    lines.extend(["", "## Links", ""])
    lines.extend(
        [
            f"- Playtest guide: {copy['source_url']}/blob/main/docs/PLAYTEST.md",
            f"- Mod Portal: {copy['mod_portal_url']}",
            f"- Homepage: {copy['homepage_url']}",
            "",
        ]
    )
    return "\n".join(lines)


def render_portal_metadata(info, copy):
    fields = {
        "MOD_PORTAL_TITLE": info["title"],
        "MOD_PORTAL_SUMMARY": copy["portal"]["summary"],
        "MOD_PORTAL_CATEGORY": copy["portal"]["category"],
        "MOD_PORTAL_TAGS": copy["portal"]["tags"],
        "MOD_PORTAL_HOMEPAGE": copy["homepage_url"],
        "MOD_PORTAL_SOURCE_URL": copy["source_url"],
    }
    return "".join(f"{key}={shlex.quote(value)}\n" for key, value in fields.items())


def write_text(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def repo_path(value):
    path = pathlib.Path(value)
    if path.is_absolute():
        return path
    return ROOT / path


def check_file(path, expected):
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return True
    try:
        display_path = path.relative_to(ROOT)
    except ValueError:
        display_path = path
    print(f"{display_path} is stale; run scripts/generate-public-assets.py.", file=sys.stderr)
    return False


def main():
    parser = argparse.ArgumentParser(description="Generate public website, release, and Mod Portal assets.")
    parser.add_argument("--check", action="store_true", help="Check that committed generated files are current.")
    parser.add_argument("--site", default=str(SITE_PATH), help="Path to write docs/index.html output.")
    parser.add_argument("--portal-description", help="Path to write generated Mod Portal description Markdown.")
    parser.add_argument("--portal-metadata", help="Path to write generated shell metadata for Mod Portal scripts.")
    parser.add_argument("--release-notes", help="Path to write generated GitHub release notes Markdown.")
    args = parser.parse_args()

    info = load_json(INFO_PATH)
    copy = load_json(COPY_PATH)
    latest_release = parse_changelog(CHANGELOG_PATH)[0]
    validate_sources(info, latest_release)

    site_content = render_site(info, copy, latest_release)

    if args.check:
        if not check_file(repo_path(args.site), site_content):
            return 1
        print("Generated public assets are current.")
        return 0

    write_text(repo_path(args.site), site_content)

    if args.portal_description:
        write_text(repo_path(args.portal_description), render_portal_description(info, copy, latest_release))

    if args.portal_metadata:
        write_text(repo_path(args.portal_metadata), render_portal_metadata(info, copy))

    if args.release_notes:
        write_text(repo_path(args.release_notes), render_release_notes(info, copy, latest_release))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
