#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

default_factorio_bin="/mnt/HC_Volume_105232828/shared/games/factorio/bin/x64/factorio"
default_headless_bin="/mnt/HC_Volume_105232828/shared/games/factorio-headless/factorio/bin/x64/factorio"
factorio_bin="${FACTORIO_BIN:-}"
if [ -z "$factorio_bin" ] && [ -x "$default_factorio_bin" ]; then
  factorio_bin="$default_factorio_bin"
fi
if [ -z "$factorio_bin" ] && [ "${ALLOW_HEADLESS_SCREENSHOTS:-0}" = "1" ] && [ -x "$default_headless_bin" ]; then
  factorio_bin="$default_headless_bin"
fi
if [ -z "$factorio_bin" ] && command -v factorio >/dev/null 2>&1; then
  factorio_bin="$(command -v factorio)"
fi
if [ -z "$factorio_bin" ] || [ ! -x "$factorio_bin" ]; then
  cat >&2 <<'EOF'
Missing graphical Factorio binary.

Set FACTORIO_BIN to the Factorio executable, for example:
  FACTORIO_BIN=/path/to/factorio/bin/x64/factorio scripts/gui-screenshots.sh

Headless builds are not the preferred screenshot path. To try one anyway:
  ALLOW_HEADLESS_SCREENSHOTS=1 SCREENSHOT_RUN_MODE=benchmark FACTORIO_BIN=/path/to/factorio/bin/x64/factorio scripts/gui-screenshots.sh
EOF
  exit 2
fi

python_bin="${PYTHON:-python3}"
package_path="$(scripts/package.sh | tail -n 1)"
output_dir="${SCREENSHOT_OUTPUT_DIR:-/tmp/turret-xp-gui-screenshots}"

find_mod_zip() {
  pattern="$1"
  shift
  for directory in "$@"; do
    if [ -n "$directory" ] && [ -d "$directory" ]; then
      find "$directory" -maxdepth 1 -type f -name "$pattern" | sort -V | tail -n 1
    fi
  done | tail -n 1
}

candidate_mod_dirs=(
  "${FACTORIO_MODS_DIR:-}"
  "$HOME/.factorio/mods"
  "/tmp"
)

flib_zip="$(find_mod_zip "flib_*.zip" "${candidate_mod_dirs[@]}")"
if [ -z "$flib_zip" ]; then
  cat >&2 <<'EOF'
Missing flib dependency zip.

Install flib into ~/.factorio/mods or set FACTORIO_MODS_DIR to a directory containing flib_*.zip.
EOF
  exit 2
fi

bullet_trails_zip="$(find_mod_zip "bullet-trails_*.zip" "${candidate_mod_dirs[@]}")"

tmpdir="$(mktemp -d /tmp/turret-xp-gui-screenshots.XXXXXX)"
cleanup() {
  if [ "${KEEP_SCREENSHOT_TMP:-0}" != "1" ]; then
    rm -rf "$tmpdir"
  else
    echo "Kept temporary directory: $tmpdir"
  fi
}
trap cleanup EXIT

mods_dir="$tmpdir/mods"
write_data_dir="$tmpdir/write-data"
config_path="$tmpdir/config.ini"
save_path="$tmpdir/screenshot-save.zip"
create_log="$tmpdir/create.log"
run_log="$tmpdir/run.log"
script_output_dir="$write_data_dir/script-output/turret-xp-gui-screenshots"
mkdir -p "$mods_dir" "$write_data_dir/saves" "$write_data_dir/script-output"

cat >"$config_path" <<EOF
; Generated by scripts/gui-screenshots.sh.
[path]
read-data=__PATH__executable__/../../data
write-data=$write_data_dir

[general]
locale=en

[other]
check-updates=false
enable-new-mods=true
EOF

cp "$package_path" "$mods_dir/"
cp "$flib_zip" "$mods_dir/"
if [ -n "$bullet_trails_zip" ]; then
  cp "$bullet_trails_zip" "$mods_dir/"
fi

screenshotter_version="$("$python_bin" -c 'import json; print(json.load(open("tests/screenshots/turret_xp_gui_screenshotter/info.json"))["version"])')"
cp -R "tests/screenshots/turret_xp_gui_screenshotter" "$mods_dir/turret_xp_gui_screenshotter_$screenshotter_version"

run_factorio() {
  log_path="$1"
  shift
  if ! "$factorio_bin" --config "$config_path" --mod-directory "$mods_dir" --disable-migration-window "$@" >"$log_path" 2>&1; then
    cat "$log_path" >&2
    exit 1
  fi
}

run_factorio "$create_log" --create "$save_path" --map-gen-seed 1

run_mode="${SCREENSHOT_RUN_MODE:-load}"
if [ "$run_mode" = "benchmark" ]; then
  run_factorio "$run_log" --benchmark "$save_path" --benchmark-ticks "${SCREENSHOT_BENCHMARK_TICKS:-180}" --benchmark-runs 1
elif [ "$run_mode" = "load" ]; then
  "$factorio_bin" --config "$config_path" --mod-directory "$mods_dir" --disable-migration-window --load-game "$save_path" >"$run_log" 2>&1 &
  factorio_pid=$!
  done_seen=0

  for _ in $(seq 1 "${SCREENSHOT_TIMEOUT_SECONDS:-45}"); do
    if grep -q "\[turret_xp_gui_screenshotter\] DONE" "$run_log"; then
      done_seen=1
      break
    fi

    if ! kill -0 "$factorio_pid" >/dev/null 2>&1; then
      break
    fi

    sleep 1
  done

  if kill -0 "$factorio_pid" >/dev/null 2>&1; then
    kill "$factorio_pid" >/dev/null 2>&1 || true
    wait "$factorio_pid" >/dev/null 2>&1 || true
  else
    wait "$factorio_pid" >/dev/null 2>&1 || true
  fi

  if [ "$done_seen" != "1" ]; then
    cat "$create_log" >&2
    cat "$run_log" >&2
    echo "GUI screenshotter did not report DONE." >&2
    exit 1
  fi
else
  echo "Unknown SCREENSHOT_RUN_MODE: $run_mode" >&2
  exit 2
fi

if ! grep -q "\[turret_xp_gui_screenshotter\] DONE" "$run_log"; then
  cat "$create_log" >&2
  cat "$run_log" >&2
  echo "GUI screenshotter did not report DONE." >&2
  exit 1
fi

if ! find "$script_output_dir" -maxdepth 1 -type f -name "*.png" | grep -q .; then
  cat "$create_log" >&2
  cat "$run_log" >&2
  echo "GUI screenshotter completed but did not produce PNG artifacts." >&2
  exit 1
fi

mkdir -p "$output_dir"
cp -R "$script_output_dir/." "$output_dir/"

echo "$output_dir"
