#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

default_factorio_bin="/mnt/HC_Volume_105232828/shared/games/factorio-headless/factorio/bin/x64/factorio"
factorio_bin="${FACTORIO_BIN:-}"
if [ -z "$factorio_bin" ] && [ -x "$default_factorio_bin" ]; then
  factorio_bin="$default_factorio_bin"
fi
if [ -z "$factorio_bin" ] && command -v factorio >/dev/null 2>&1; then
  factorio_bin="$(command -v factorio)"
fi
if [ -z "$factorio_bin" ] || [ ! -x "$factorio_bin" ]; then
  cat >&2 <<'EOF'
Missing Factorio headless binary.

Set FACTORIO_BIN to the Factorio executable, for example:
  FACTORIO_BIN=/path/to/factorio/bin/x64/factorio scripts/test-headless.sh
EOF
  exit 2
fi

factorio_executable_dir="$(cd "$(dirname "$factorio_bin")" && pwd -P)"
factorio_read_data_dir=""
for candidate in \
  "$factorio_executable_dir/../../data" \
  "$factorio_executable_dir/../data"
do
  if [ -d "$candidate/core" ]; then
    factorio_read_data_dir="$(cd "$candidate" && pwd -P)"
    break
  fi
done

if [ -z "$factorio_read_data_dir" ]; then
  cat >&2 <<EOF
Missing Factorio data directory.

Could not find the Factorio core package beside:
  $factorio_bin
EOF
  exit 2
fi

python_bin="${PYTHON:-python3}"
package_path="$(scripts/package.sh | tail -n 1)"

find_mod_zip() {
  pattern="$1"
  shift
  for directory in "$@"; do
    if [ -n "$directory" ] && [ -d "$directory" ]; then
      find "$directory" -maxdepth 1 -type f -name "$pattern" | sort -V | tail -n 1
    fi
  done | tail -n 1
}

candidate_mod_dirs=(
  "${FACTORIO_MODS_DIR:-}"
  "$HOME/Library/Application Support/factorio/mods"
  "$HOME/.factorio/mods"
  "/tmp"
)

flib_zip="$(find_mod_zip "flib_*.zip" "${candidate_mod_dirs[@]}")"
if [ -z "$flib_zip" ]; then
  cat >&2 <<'EOF'
Missing flib dependency zip.

Install flib into ~/.factorio/mods or set FACTORIO_MODS_DIR to a directory containing flib_*.zip.
EOF
  exit 2
fi

bullet_trails_zip="$(find_mod_zip "bullet-trails_*.zip" "${candidate_mod_dirs[@]}")"

tmpdir="$(mktemp -d /tmp/turret-xp-headless.XXXXXX)"
cleanup() {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

mods_dir="$tmpdir/mods"
write_data_dir="$tmpdir/write-data"
config_path="$tmpdir/config.ini"
mkdir -p "$mods_dir" "$write_data_dir/saves" "$write_data_dir/script-output"

cat >"$config_path" <<EOF
; Generated by scripts/test-headless.sh.
[path]
read-data=$factorio_read_data_dir
write-data=$write_data_dir

[general]
locale=en

[other]
check-updates=false
enable-new-mods=true
EOF

cp "$package_path" "$mods_dir/"
cp "$flib_zip" "$mods_dir/"
if [ -n "$bullet_trails_zip" ]; then
  cp "$bullet_trails_zip" "$mods_dir/"
fi

test_version="$("$python_bin" -c 'import json; print(json.load(open("tests/headless/turret_xp_headless_tests/info.json"))["version"])')"
cp -R "tests/headless/turret_xp_headless_tests" "$mods_dir/turret_xp_headless_tests_$test_version"

save_path="$tmpdir/headless-test.zip"
create_log="$tmpdir/create.log"
benchmark_log="$tmpdir/benchmark.log"

run_factorio() {
  log_path="$1"
  shift
  if ! "$factorio_bin" --config "$config_path" --mod-directory "$mods_dir" --disable-migration-window "$@" >"$log_path" 2>&1; then
    cat "$log_path" >&2
    exit 1
  fi
}

run_factorio "$create_log" --create "$save_path" --map-gen-seed 1
run_factorio "$benchmark_log" --benchmark "$save_path" --benchmark-ticks 1200 --benchmark-runs 1

if ! grep -q "\[turret_xp_headless_tests\] PASS" "$benchmark_log"; then
  cat "$create_log" >&2
  cat "$benchmark_log" >&2
  echo "Headless tests did not report PASS." >&2
  exit 1
fi

budget_line="$(grep -m 1 "\[turret_xp_headless_tests\] prototype budget:" "$create_log" | sed 's/^.*\[turret_xp_headless_tests\] //' || true)"
if [ -n "$budget_line" ]; then
  echo "$budget_line"
fi

remote_policy_mods_dir="$tmpdir/remote-policy-mods"
mkdir -p "$remote_policy_mods_dir"
cp "$package_path" "$remote_policy_mods_dir/"
cp "$flib_zip" "$remote_policy_mods_dir/"
if [ -n "$bullet_trails_zip" ]; then
  cp "$bullet_trails_zip" "$remote_policy_mods_dir/"
fi

remote_policy_version="$("$python_bin" -c 'import json; print(json.load(open("tests/headless/turret_xp_remote_policy_tests/info.json"))["version"])')"
cp -R "tests/headless/turret_xp_remote_policy_tests" "$remote_policy_mods_dir/turret_xp_remote_policy_tests_$remote_policy_version"

mods_dir="$remote_policy_mods_dir"
remote_policy_save_path="$tmpdir/remote-policy-test.zip"
remote_policy_create_log="$tmpdir/remote-policy-create.log"
run_factorio "$remote_policy_create_log" --create "$remote_policy_save_path" --map-gen-seed 1

if ! grep -q "\[turret_xp_remote_policy_tests\] PASS" "$remote_policy_create_log"; then
  cat "$remote_policy_create_log" >&2
  echo "Remote policy smoke test did not report PASS." >&2
  exit 1
fi

echo "Headless tests passed."
